# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: ./env/Script/activate.bat

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

executors:
  docker-executor: 
    docker:
    - image: cimg/python:3.10.6

jobs:
  build-with-docker:
    executor: docker-executor
    steps:
    - build

workflows: 
  build-with-docker:
    jobs:
    - build-with-docker