# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  build:
    steps:
      - checkout
      - run : pip install -r requirements.txt
  linting:
    steps: 
      - run : flake8
  tests:
    steps: 
      - run : pytest
 




# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

executors:
  docker-executor: 
    docker:
    - image: cimg/python:3.10.6

jobs:
  build-with-docker:
    executor: docker-executor
    steps:
    - build
    - linting
    - tests

workflows: 
  build-with-docker:
    jobs:
    - build-with-docker